apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/SAI/nexus_pv"  #hostpath can be defined as per your requirement.  Technically you should not use the hostpath :D

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi